// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtyeqNa8siMPTIGFRoR-Pjk8SyYj6pC8k',
    appId: '1:300771054827:web:11e251cd35172e453cdaae',
    messagingSenderId: '300771054827',
    projectId: 'flutter-firebase-xyz123abc',
    authDomain: 'flutter-firebase-xyz123abc.firebaseapp.com',
    storageBucket: 'flutter-firebase-xyz123abc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMsYeb2Dyxf9rSdkCiN00TIiqBDTVBiKg',
    appId: '1:300771054827:android:2b93e6a5291178bf3cdaae',
    messagingSenderId: '300771054827',
    projectId: 'flutter-firebase-xyz123abc',
    storageBucket: 'flutter-firebase-xyz123abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHvB2Avge_od4nm60YHyvPhR5_1ye61xc',
    appId: '1:300771054827:ios:eb91d289931cf6283cdaae',
    messagingSenderId: '300771054827',
    projectId: 'flutter-firebase-xyz123abc',
    storageBucket: 'flutter-firebase-xyz123abc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHvB2Avge_od4nm60YHyvPhR5_1ye61xc',
    appId: '1:300771054827:ios:eb91d289931cf6283cdaae',
    messagingSenderId: '300771054827',
    projectId: 'flutter-firebase-xyz123abc',
    storageBucket: 'flutter-firebase-xyz123abc.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtyeqNa8siMPTIGFRoR-Pjk8SyYj6pC8k',
    appId: '1:300771054827:web:28963b72a34033223cdaae',
    messagingSenderId: '300771054827',
    projectId: 'flutter-firebase-xyz123abc',
    authDomain: 'flutter-firebase-xyz123abc.firebaseapp.com',
    storageBucket: 'flutter-firebase-xyz123abc.firebasestorage.app',
  );

}